-- AlterEnum
ALTER TYPE "SalesOrderStatus" ADD VALUE IF NOT EXISTS 'SUBMITTED';
ALTER TYPE "SalesOrderStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "SalesOrderStatus" ADD VALUE IF NOT EXISTS 'ALLOCATED';
ALTER TYPE "SalesOrderStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_FULFILLED';
ALTER TYPE "SalesOrderStatus" ADD VALUE IF NOT EXISTS 'FULFILLED';
ALTER TYPE "SalesOrderStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "SalesOrderStatus" ADD VALUE IF NOT EXISTS 'VOIDED';

-- AlterEnum
ALTER TYPE "DeliveryOrderStatus" ADD VALUE IF NOT EXISTS 'DISPATCHED';
ALTER TYPE "DeliveryOrderStatus" ADD VALUE IF NOT EXISTS 'CLOSED';

-- AlterTable
ALTER TABLE "sales_orders" 
  ADD COLUMN IF NOT EXISTS "approved_by_user_id" UUID,
  ADD COLUMN IF NOT EXISTS "approved_at" TIMESTAMPTZ(6),
  ADD COLUMN IF NOT EXISTS "rejected_by_user_id" UUID,
  ADD COLUMN IF NOT EXISTS "rejected_at" TIMESTAMPTZ(6),
  ADD COLUMN IF NOT EXISTS "rejection_reason" TEXT,
  ADD COLUMN IF NOT EXISTS "cancelled_by_user_id" UUID,
  ADD COLUMN IF NOT EXISTS "cancelled_at" TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "delivery_orders"
  ADD COLUMN IF NOT EXISTS "dispatched_at" TIMESTAMPTZ(6),
  ADD COLUMN IF NOT EXISTS "cancellation_reason" TEXT;
